import java.util.Scanner;
import java.text.DecimalFormat;
/**
*computes value generated by an expression.
*
*Project 3
*@CarsonBarnett-COMP1210-003
*@1/28/19
*/
public class ExpressionEvaluator {
/**
*evaluates expression.
*@param args command line argument (not used)
*/
   public static void main(String [] args) {
      Scanner userInput = new Scanner(System.in);
      double x = 0;
      double n1 = 0;
      double n2 = 0;
      double n3 = 0;
      double nfinal = 0;
      double d = 0;
      double result = 0;
      System.out.print("Enter a value for x: ");
      x = Double.parseDouble(userInput.nextLine()); //input x
      n1 = (1.2 * (Math.pow(x, 3.0))) - (10 * x) + 1; //performs math in num
      n2 = (5 * Math.pow(x, 4)) - (7 * Math.pow(x, 3));
      n3 = (Math.pow(n2, 2)) + (Math.abs(n1));
      nfinal = Math.sqrt(n3); //final numerator before final calculation
      d = Math.pow(x, 2) + 10; //denominator before final calculation
      result = nfinal / d;
      System.out.println("Result: " + result); //final result
      String resultConverted = Double.toString(result);
      //converts result type double to a string
      int index = resultConverted.indexOf(".");
      int rightOfDecimal = resultConverted.length() - index - 1; 
     //# of characters to the right of the decimal point
      int leftOfDecimal = resultConverted.length() - rightOfDecimal - 1;
      //# of characters to the left of the decimal point
      System.out.println("# of characters to left of decimal point: "
         + leftOfDecimal);
      System.out.println("# of characters to right of decimal point: "
         + rightOfDecimal);
      DecimalFormat formattedResult = new DecimalFormat("#,##0.0###");
      System.out.println("Formatted Result: " + formattedResult.format(result));
   }
}